from site_scons import *
COREPATH = '../../core'

env = Environment(CPPPATH=CPPATH+['./', COREPATH+'/src' ])

modules = [
    Glob('./*.cpp'),
]

env.Program('./main', modules, LIBS=['engine']+SDL_LIBS, LIBPATH=COREPATH, CXXFLAGS=COMMON_CXX_FLAGS, )
env.Append(LINKFLAGS=['-rdynamic'])
